import { filterSchemaInterface } from '@/app/_interface';
import { routeIdGenerator } from '@/app/_utils/routeIdGenerator';

export const filterList: filterSchemaInterface[][] = routeIdGenerator([
  [
    {
      title: 'جستجو',
      search: true,
      accordion: false,
      placeholder: 'جستجو در تایپ شناسی ...',
      type: 'search',
    },
    {
      type: 'line',
      accordion: false,
      search: false,
    },
    {
      type: 'normal',
      accordion: true,
      title: 'کشور',
      search: true,
      parentQuery: 'country',
      placeholder: 'در کشور ها جستجو کنید...',
      items: [
        {
          query: 'ALL',
          title: 'همه',
        },
        { query: '1', title: 'آروبا' },
        { query: '2', title: 'آنتیگوا و باربودا' },
        { query: '3', title: 'امارات متحده عربی' },
        { query: '4', title: 'افغانستان' },
        { query: '5', title: 'الجزایر' },
        { query: '6', title: 'آذربایجان' },
        { query: '7', title: 'آلبانی' },
        { query: '8', title: 'ارمنستان' },
        { query: '9', title: 'آندورا' },
        { query: '10', title: 'آنگولا' },
        { query: '11', title: 'ساموای آمریکایی' },
        { query: '12', title: 'آرژانتین' },
        { query: '13', title: 'استرالیا' },
        { query: '14', title: 'اشکمور و جزایر کارتیه' },
        { query: '15', title: 'اتریش' },
        { query: '16', title: 'آنگویلا' },
        { query: '17', title: 'جزایر الند' },
        { query: '18', title: 'قطب جنوب' },
        { query: '19', title: 'بحرین' },
        { query: '20', title: 'باربادوس' },
        { query: '21', title: 'بوتسوانا' },
        { query: '22', title: 'برمودا' },
        { query: '23', title: 'بلژیک' },
        { query: '24', title: 'باهاما، The' },
        { query: '25', title: 'بنگلادش' },
        { query: '26', title: 'بلیز' },
        { query: '27', title: 'بوسنی و هرزگوین' },
        { query: '28', title: 'بولیوی' },
        { query: '29', title: 'میانمار' },
        { query: '30', title: 'بنین' },
        { query: '31', title: 'بلاروس' },
        { query: '32', title: 'جزایر سلیمان' },
        { query: '33', title: 'جزیره ناواسا' },
        { query: '34', title: 'برزیل' },
        { query: '35', title: 'باساس دا هند' },
        { query: '36', title: 'بوتان' },
        { query: '37', title: 'بلغارستان' },
        { query: '38', title: 'جزیره Bouvet' },
        { query: '39', title: 'برونئی' },
        { query: '40', title: 'بوروندی' },
        { query: '41', title: 'کانادا' },
        { query: '42', title: 'کامبوج' },
        { query: '43', title: 'چاد' },
        { query: '44', title: 'سری لانکا' },
        { query: '45', title: 'کنگو، جمهوری' },
        { query: '46', title: 'کنگو، جمهوری دموکراتیک' },
        { query: '47', title: 'چين' },
        { query: '48', title: 'شیلی' },
        { query: '49', title: 'جزایر کیمن' },
        { query: '50', title: 'جزایر کوکوس (کایلینگ)' },
        { query: '51', title: 'کامرون' },
        { query: '52', title: 'کومور' },
        { query: '53', title: 'کلمبیا' },
        { query: '54', title: 'جزایر ماریانای شمالی' },
        { query: '55', title: 'جزایر دریای مرجانی' },
        { query: '56', title: 'کاستاریکا' },
        { query: '57', title: 'جمهوری آفریقای مرکزی' },
        { query: '58', title: 'کوبا' },
        { query: '59', title: 'کیپ ورد' },
        { query: '60', title: 'جزایر کوک' },
        { query: '61', title: 'قبرس' },
        { query: '62', title: 'دانمارک' },
        { query: '63', title: 'جیبوتی' },
        { query: '64', title: 'دومینیکا' },
        { query: '65', title: 'جزیره جارویس' },
        { query: '66', title: 'جمهوری دومینیکن' },
        { query: '67', title: 'منطقه ممنوعه Dhekelia' },
        { query: '68', title: 'اکوادور' },
        { query: '69', title: 'مصر' },
        { query: '70', title: 'ایرلند' },
        { query: '71', title: 'گینه استوایی' },
        { query: '72', title: 'استونی' },
        { query: '73', title: 'اریتره' },
        { query: '74', title: 'السالوادور' },
        { query: '75', title: 'اتیوپی' },
        { query: '76', title: 'جزیره اروپا' },
        { query: '77', title: 'جمهوری چک' },
        { query: '78', title: 'گویان فرانسه' },
        { query: '79', title: 'فنلاند' },
        { query: '80', title: 'فیجی' },
        { query: '81', title: 'جزایر فالکلند (جزایر مالویناس)' },
        { query: '82', title: 'میکرونزی، ایالات فدرال' },
        { query: '83', title: 'جزایر فارو' },
        { query: '84', title: 'پلینزی فرانسه' },
        { query: '85', title: 'جزیره بیکر' },
        { query: '86', title: 'فرانسه' },
        { query: '87', title: 'زمینهای جنوب و جنوب قطب جنوب فرانسه' },
        { query: '88', title: 'گامبیا، The' },
        { query: '89', title: 'گابن' },
        { query: '90', title: 'جورجیا' },
        { query: '91', title: 'غنا' },
        { query: '92', title: 'جبل الطارق' },
        { query: '93', title: 'گرانادا' },
        { query: '94', title: 'گورنسی' },
        { query: '95', title: 'گرینلند' },
        { query: '96', title: 'آلمان' },
        { query: '97', title: 'جزایر گلوریوزو' },
        { query: '98', title: 'گوادلوپ' },
        { query: '99', title: 'گوام' },
        { query: '100', title: 'یونان' },
        { query: '101', title: 'گواتمالا' },
        { query: '102', title: 'گینه' },
        { query: '103', title: 'گایانا' },
        { query: '104', title: 'نوار غزه' },
        { query: '105', title: 'هائیتی' },
        { query: '106', title: 'هنگ کنگ' },
        { query: '107', title: 'جزایر هرد و جزایر مک دونالد' },
        { query: '108', title: 'هندوراس' },
        { query: '109', title: 'جزیره Howland' },
        { query: '110', title: 'کرواسی' },
        { query: '111', title: 'مجارستان' },
        { query: '112', title: 'ایسلند' },
        { query: '113', title: 'اندونزی' },
        { query: '114', title: 'جزیره من' },
        { query: '115', title: 'هندوستان' },
        { query: '116', title: 'قلمرو اقیانوس هند بریتانیا' },
        { query: '117', title: 'جزیره Clipperton' },
        { query: '118', title: 'ایران' },
        { query: '119', title: 'اسرائيل' },
        { query: '120', title: 'ایتالیا' },
        { query: '121', title: 'ساحل عاج' },
        { query: '122', title: 'عراق' },
        { query: '123', title: 'ژاپن' },
        { query: '124', title: 'جرسی' },
        { query: '125', title: 'جامائیکا' },
        { query: '126', title: 'Jan Mayen' },
        { query: '127', title: 'اردن' },
        { query: '128', title: 'جانستون اتول' },
        { query: '129', title: 'جزیره خوان جزیره نوا' },
        { query: '130', title: 'کنیا' },
        { query: '131', title: 'قرقیزستان' },
        { query: '132', title: 'کره شمالی' },
        { query: '133', title: 'کینگمن ریف' },
        { query: '134', title: 'کیریباتی' },
        { query: '135', title: 'کره جنوبی' },
        { query: '136', title: 'جزیره کریسمس' },
        { query: '137', title: 'کویت' },
        { query: '138', title: 'کوزوو' },
        { query: '139', title: 'قزاقستان' },
        { query: '140', title: 'لائوس' },
        { query: '141', title: 'لبنان' },
        { query: '142', title: 'لتونی' },
        { query: '143', title: 'لیتوانی' },
        { query: '144', title: 'لیبریا' },
        { query: '145', title: 'اسلواکی' },
        { query: '146', title: 'پالمیرا اتل' },
        { query: '147', title: 'لیختن اشتاین' },
        { query: '148', title: 'لسوتو' },
        { query: '149', title: 'لوکزامبورگ' },
        { query: '150', title: 'عرب لیبی' },
        { query: '151', title: 'ماداگاسکار' },
        { query: '152', title: 'مارتینیک' },
        { query: '153', title: 'ماکائو' },
        { query: '154', title: 'مولداوی، جمهوری' },
        { query: '155', title: 'مایوت' },
        { query: '156', title: 'مغولستان' },
        { query: '157', title: 'مونتسرات' },
        { query: '158', title: 'مالاوی' },
        { query: '159', title: 'مونته نگرو' },
        { query: '160', title: 'جمهوری مقدونیه یوگسلاوی سابق' },
        { query: '161', title: 'مالزی' },
        { query: '162', title: 'موناکو' },
        { query: '163', title: 'مراکش' },
        { query: '164', title: 'موریس' },
        { query: '165', title: 'جزایر میدوی' },
        { query: '166', title: 'موریتانی' },
        { query: '167', title: 'مالت' },
        { query: '168', title: 'عمان' },
        { query: '169', title: 'مالدیو' },
        { query: '170', title: 'مکزیک' },
        { query: '171', title: 'مالزی' },
        { query: '172', title: 'موزامبیک' },
        { query: '173', title: 'کالدونیای جدید' },
        { query: '174', title: 'نیو' },
        { query: '175', title: 'جزیره نورفولک' },
        { query: '176', title: 'نیجر' },
        { query: '177', title: 'وانواتو' },
        { query: '178', title: 'نیجریه' },
        { query: '179', title: 'هلند' },
        { query: '180', title: 'هیچ مردی زمین نیست' },
        { query: '181', title: 'نروژ' },
        { query: '182', title: 'نپال' },
        { query: '183', title: 'نائورو' },
        { query: '184', title: 'سورینام' },
        { query: '185', title: 'آنتیل هلند' },
        { query: '186', title: 'نیکاراگوئه' },
        { query: '187', title: 'نیوزلند' },
        { query: '188', title: 'پاراگوئه' },
        { query: '189', title: 'جزایر پیتکرن' },
        { query: '190', title: 'پرو' },
        { query: '191', title: 'جزایر پاراسل' },
        { query: '192', title: 'جزایر اسپارتلی' },
        { query: '193', title: 'پاکستان' },
        { query: '194', title: 'لهستان' },
        { query: '195', title: 'پاناما' },
        { query: '196', title: 'کشور پرتغال' },
        { query: '197', title: 'پاپوآ گینه نو' },
        { query: '198', title: 'پالائو' },
        { query: '199', title: 'گینه بیسائو' },
        { query: '200', title: 'قطر' },
        { query: '201', title: 'تجدید دیدار' },
        { query: '202', title: 'صربستان' },
        { query: '203', title: 'جزایر مارشال' },
        { query: '204', title: 'سنت مارتین' },
        { query: '205', title: 'رومانی' },
        { query: '206', title: 'فیلیپین' },
        { query: '207', title: 'پورتوریکو' },
        { query: '208', title: 'روسیه' },
        { query: '209', title: 'رواندا' },
        { query: '210', title: 'عربستان سعودی' },
        { query: '211', title: 'سنت پیر و میکلون' },
        { query: '212', title: 'سنت کیتس و نویس' },
        { query: '213', title: 'سیشل' },
        { query: '214', title: 'آفریقای جنوبی' },
        { query: '215', title: 'سنگال' },
        { query: '216', title: 'سنت هلن' },
        { query: '217', title: 'اسلوونی' },
        { query: '218', title: 'سیرا لئون' },
        { query: '219', title: 'سان مارینو' },
        { query: '220', title: 'سنگاپور' },
        { query: '221', title: 'سومالی' },
        { query: '222', title: 'اسپانیا' },
        { query: '223', title: 'سنت لوسیا' },
        { query: '224', title: 'سودان' },
        { query: '225', title: 'اسباب بازی' },
        { query: '226', title: 'سوئد' },
        { query: '227', title: 'جنوب گرجستان و جزایر' },
        { query: '228', title: 'جمهوری عربی سوریه' },
        { query: '229', title: 'سوئیس' },
        { query: '230', title: 'ترینیداد و توباگو' },
        { query: '231', title: 'جزیره ترولین' },
        { query: '232', title: 'تایلند' },
        { query: '233', title: 'تاجیکستان' },
        { query: '234', title: 'جزایر ترکس و کایکوس' },
        { query: '235', title: 'توکلو' },
        { query: '236', title: 'تونگا' },
        { query: '237', title: 'رفتن' },
        { query: '238', title: 'سائوتومه و پرنسیپه' },
        { query: '239', title: 'تونس' },
        { query: '240', title: 'تیمور شرقی' },
        { query: '241', title: 'بوقلمون' },
        { query: '242', title: 'توووالو' },
        { query: '243', title: 'تایوان' },
        { query: '244', title: 'ترکمنستان' },
        { query: '245', title: 'تانزانیا، جمهوری متحده' },
        { query: '246', title: 'اوگاندا' },
        { query: '247', title: 'انگلستان' },
        { query: '248', title: 'اوکراین' },
        { query: '249', title: 'ایالات متحده' },
        { query: '250', title: 'بورکینافاسو' },
        { query: '251', title: 'اروگوئه' },
        { query: '252', title: 'ازبکستان' },
        { query: '253', title: 'سنت وینسنت و گرنادین' },
        { query: '254', title: 'ونزوئلا' },
        { query: '255', title: 'جزایر ویرجین بریتانیا' },
        { query: '256', title: 'ویتنام' },
        { query: '257', title: 'جزایر ویرجین (ایالات متحده)' },
        { query: '258', title: 'مقدس (واتیکان)' },
        { query: '259', title: 'نامیبیا' },
        { query: '260', title: 'بانک غرب' },
        { query: '261', title: 'والیس و فوتونا' },
        { query: '262', title: 'صحرای غربی' },
        { query: '263', title: 'جزیره ویک' },
        { query: '264', title: 'ساموآ' },
        { query: '265', title: 'سوازیلند' },
        { query: '266', title: 'صربستان و مونته نگرو' },
        { query: '267', title: 'یمن' },
        { query: '268', title: 'زامبیا' },
        { query: '269', title: 'زیمبابوه' },
      ],
    },
    {
      type: 'checkbox',
      accordion: true,
      title: 'افراد مشهور',
      search: false,
      parentQuery: 'famous_people',
      items: [
        {
          query: 'ALL',
          title: 'همه',
        },
        {
          query: '3',
          title: 'بازیگر',
        },
        {
          query: '5',
          title: 'تلوزیون',
        },
        {
          query: '6',
          title: 'ورزشکار',
        },
        {
          query: '7',
          title: 'سیاست مدار',
        },
        {
          query: '8',
          title: 'شاعر',
        },
        {
          query: '9',
          title: 'هنرمند',
        },
        {
          query: '10',
          title: 'فعال مجازی',
        },
        {
          query: '11',
          title: 'دانشمند',
        },
        {
          query: '12',
          title: 'مذهب',
        },
        {
          query: '13',
          title: 'کسب و کار',
        },
      ],
    },
    {
      type: 'checkbox',
      accordion: true,
      title: 'شخصیت های تخیلی',
      parentQuery: 'finctional_character',
      search: false,
      items: [
        {
          query: 'ALL',
          title: 'همه',
        },
        {
          title: 'ابر قهرمانان',
          query: 'heros',
        },
        {
          title: 'سریال',
          query: 'series',
        },
        {
          title: 'سینمایی',
          query: 'movie',
        },
        {
          title: 'کارتون',
          query: 'cartoon',
        },
        {
          title: 'کمیک',
          query: 'comic',
        },
        {
          title: 'انیمه و مانگو',
          query: 'anime',
        },
        {
          title: 'تلوزیون',
          query: 'tv',
        },
        {
          title: 'کتاب',
          query: 'book',
        },
        {
          title: 'بازی',
          query: 'game',
        },
        {
          title: 'تئاتر',
          query: 'Theater',
        },
      ],
    },
    {
      type: 'checkbox',
      accordion: true,
      title: 'سرگرمی',
      parentQuery: 'intertainment',
      search: false,
      items: [
        {
          query: 'ALL',
          title: 'همه',
        },
        {
          title: 'حیوانات',
          query: 'animals',
        },
        {
          title: 'گیاهان',
          query: 'plants',
        },
        {
          title: 'اشیا',
          query: 'things',
        },
        {
          title: 'کشور',
          query: 'country',
        },
        {
          title: 'موسیقی',
          query: 'song',
        },
        {
          title: 'تجارب',
          query: 'experiences',
        },
        {
          title: 'نظریه ها',
          query: 'reviews',
        },
        {
          title: 'موسسات',
          query: 'institutes',
        },
        {
          title: 'دیالوگ',
          query: 'dialog',
        },
        {
          title: 'میم',
          query: 'mim',
        },
        {
          title: 'آرت',
          query: 'art',
        },
      ],
    },
    {
      type: 'line',
      accordion: false,
      search: false,
    },
    {
      title: 'تایپ های شخصیتی',
      search: false,
      accordion: false,
      items: [],
      type: 'title',
    },
    {
      type: 'checkbox',
      accordion: true,
      title: 'تیپ های شخصیتی MBTI',
      search: false,
      parentQuery: 'mbti',
      items: [
        {
          title: 'همه',
          query: 'ALL',
        },
        {
          title: 'Estj',
          query: '1',
        },
        {
          title: 'Istj',
          query: '2',
        },
        {
          title: 'Esfj',
          query: '3',
        },
        {
          title: 'Isfj',
          query: '4',
        },
        {
          title: 'Entj',
          query: '5',
        },
        {
          title: 'Intj',
          query: '6',
        },
        {
          title: 'Entp',
          query: '7',
        },
        {
          title: 'Intp',
          query: '8',
        },
        {
          title: 'Estp',
          query: '9',
        },
        {
          title: 'Istp',
          query: '10',
        },
        {
          title: 'Esfp',
          query: '11',
        },
        {
          title: 'Isfp',
          query: '12',
        },
        {
          title: 'Enfj',
          query: '13',
        },
        {
          title: 'Infj',
          query: '14',
        },
        {
          title: 'Enfp',
          query: '15',
        },
        {
          title: 'Infp',
          query: '16',
        },
      ],
    },
    {
      type: 'checkbox',
      accordion: true,
      title: 'تیپ های شخصیتی انیاگرام',
      search: false,
      parentQuery: 'aniagram',
      items: [
        {
          title: 'همه',
          query: 'ALL',
        },
        {
          query: '1',
          title: '1w2',
        },
        {
          query: '2',
          title: '1w9',
        },
        {
          query: '3',
          title: '2w1',
        },
        {
          query: '4',
          title: '2w3',
        },
        {
          query: '5',
          title: '3w2',
        },
        {
          query: '6',
          title: '3w4',
        },
        {
          query: '7',
          title: '4w3',
        },
        {
          query: '8',
          title: '4w5',
        },
        {
          query: '9',
          title: '5w4',
        },
        {
          query: '10',
          title: '5w6',
        },
        {
          query: '11',
          title: '6w5',
        },
        {
          query: '12',
          title: '6w7',
        },
        {
          query: '13',
          title: '7w6',
        },
        {
          query: '14',
          title: '8w7',
        },
        {
          query: '15',
          title: '8w9',
        },
        {
          query: '16',
          title: '9w8',
        },
        {
          query: '17',
          title: '9w1',
        },
      ],
    },
    {
      type: 'checkbox',
      accordion: true,
      title: 'غرایز انیاگرام',
      parentQuery: 'aniagramInstinct',
      search: false,
      items: [
        {
          query: 'ALL',
          title: 'همه',
        },
        {
          query: '1',
          title: 'So/sp',
        },
        {
          query: '2',
          title: 'Sp/so',
        },
        {
          query: '3',
          title: 'Sx/so',
        },
        {
          query: '4',
          title: 'So/sx',
        },
        {
          query: '5',
          title: 'Sx/sp',
        },
        {
          query: '6',
          title: 'Sp/sx',
        },
      ],
    },
    {
      type: 'checkbox',
      accordion: true,
      title: 'مزاج',
      search: false,
      parentQuery: 'temperment',
      items: [
        {
          query: 'ALL',
          title: 'همه',
        },
        {
          query: '1',
          title: 'بلغم',
        },
        {
          query: '2',
          title: 'سودا',
        },
        {
          query: '3',
          title: 'صفرا',
        },
        {
          query: '4',
          title: 'دم',
        },
      ],
    },
  ],
  [
    {
      title: 'جستجوی روابط تایپ ها',
      search: false,
      accordion: false,
      items: [],
      type: 'title',
    },
    {
      type: 'normal',
      accordion: true,
      title: 'نوع رابطه',
      search: false,
      parentQuery: 'realationType',
      items: [
        {
          query: 'ALL',
          title: 'همه',
        },
        {
          title: 'روابط عاشقانه',
          query: 'روابط عاشقانه',
        },
        {
          title: 'روابط خانوادگی',
          query: 'روابط خانوادگی',
        },
        {
          title: 'روابط دوستانه',
          query: 'روابط دوستانه',
        },
        {
          title: 'روابط کاری',
          query: 'روابط کاری',
        },
      ],
    },
    {
      type: 'select',
      accordion: true,
      title: 'روابط بین تایپ های MBTI',
      parentQuery: 'relation_mbti',
      search: false,
      items: [
        {
          title: 'estj',
          query: 'estj',
        },
        {
          title: 'istj',
          query: 'istj',
        },
        {
          title: 'esfj',
          query: 'esfj',
        },
        {
          title: 'isfj',
          query: 'isfj',
        },
        {
          title: 'entj',
          query: 'entj',
        },
        {
          title: 'intj',
          query: 'intj',
        },
        {
          title: 'entp',
          query: 'entp',
        },
        {
          title: 'intp',
          query: 'intp',
        },
        {
          title: 'estp',
          query: 'estp',
        },
        {
          title: 'istp',
          query: 'istp',
        },
        {
          title: 'esfp',
          query: 'esfp',
        },
        {
          title: 'isfp',
          query: 'isfp',
        },
        {
          title: 'enfj',
          query: 'enfj',
        },
        {
          title: 'infj',
          query: 'infj',
        },
        {
          title: 'enfp',
          query: 'enfp',
        },
        {
          title: 'infp',
          query: 'infp',
        },
      ],
    },
    {
      type: 'select',
      accordion: true,
      title: 'روابط بین تایپهای انیاگرام',
      search: false,
      parentQuery: 'relation_aniagram',
      items: [
        {
          title: '1w2',
          query: '1w2',
        },
        {
          title: '1w9',
          query: '1w9',
        },
        {
          title: '2w1',
          query: '2w1',
        },
        {
          title: '2w3',
          query: '2w3',
        },
        {
          title: '3w2',
          query: '3w2',
        },
        {
          title: '3w4',
          query: '3w4',
        },
        {
          title: '4w3',
          query: '4w3',
        },
        {
          title: '4w5',
          query: '4w5',
        },
        {
          title: '5w4',
          query: '5w4',
        },
        {
          title: '5w6',
          query: '5w6',
        },
        {
          title: '6w5',
          query: '6w5',
        },
        {
          title: '6w7',
          query: '6w7',
        },
        {
          title: '7w6',
          query: '7w6',
        },
        {
          title: '8w7',
          query: '8w7',
        },
        {
          title: '8w9',
          query: '8w9',
        },
        {
          title: '9w8',
          query: '9w8',
        },
        {
          title: '9w1',
          query: '9w1',
        },
      ],
    },
  ],
  [
    {
      title: 'جستجوی پیشنهادات',
      search: false,
      accordion: false,
      items: [],
      type: 'title',
    },
    {
      type: 'normal',
      accordion: true,
      title: 'نوع پیشنهاد',
      parentQuery: 'suggestion_type',
      search: false,
      items: [
        {
          query: 'ALL',
          title: 'همه',
        },
        {
          query: 'movie',
          title: 'فیلم',
        },
        {
          query: 'book',
          title: 'کتاب',
        },
        {
          query: 'song',
          title: 'موسیقی',
        },
      ],
    },
    {
      type: 'checkbox',
      accordion: true,
      title: 'تایپهای mbti',
      search: false,
      parentQuery: 'suggestion_mbti',
      items: [
        {
          query: 'ALL',
          title: 'همه',
        },
        {
          title: 'estj',
          query: 'estj',
        },
        {
          title: 'istj',
          query: 'istj',
        },
        {
          title: 'esfj',
          query: 'esfj',
        },
        {
          title: 'isfj',
          query: 'isfj',
        },
        {
          title: 'entj',
          query: 'entj',
        },
        {
          title: 'intj',
          query: 'intj',
        },
        {
          title: 'entp',
          query: 'entp',
        },
        {
          title: 'intp',
          query: 'intp',
        },
        {
          title: 'estp',
          query: 'estp',
        },
        {
          title: 'istp',
          query: 'istp',
        },
        {
          title: 'esfp',
          query: 'esfp',
        },
        {
          title: 'isfp',
          query: 'isfp',
        },
        {
          title: 'enfj',
          query: 'enfj',
        },
        {
          title: 'infj',
          query: 'infj',
        },
        {
          title: 'enfp',
          query: 'enfp',
        },
        {
          title: 'infp',
          query: 'infp',
        },
      ],
    },
    {
      type: 'checkbox',
      accordion: true,
      title: 'تایپهای ایناگرام',
      parentQuery: 'suggestion_aniagram',
      search: false,
      items: [
        {
          query: 'ALL',
          title: 'همه',
        },
        {
          title: '1w2',
          query: '1w2',
        },
        {
          title: '1w9',
          query: '1w9',
        },
        {
          title: '2w1',
          query: '2w1',
        },
        {
          title: '2w3',
          query: '2w3',
        },
        {
          title: '3w2',
          query: '3w2',
        },
        {
          title: '3w4',
          query: '3w4',
        },
        {
          title: '4w3',
          query: '4w3',
        },
        {
          title: '4w5',
          query: '4w5',
        },
        {
          title: '5w4',
          query: '5w4',
        },
        {
          title: '5w6',
          query: '5w6',
        },
        {
          title: '6w5',
          query: '6w5',
        },
        {
          title: '6w7',
          query: '6w7',
        },
        {
          title: '7w6',
          query: '7w6',
        },
        {
          title: '8w7',
          query: '8w7',
        },
        {
          title: '8w9',
          query: '8w9',
        },
        {
          title: '9w8',
          query: '9w8',
        },
        {
          title: '9w1',
          query: '9w1',
        },
      ],
    },
  ],
]);
